AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image Resizer & Optimizer API using FastAPI and AWS Lambda

Globals:
  Function:
    Timeout: 10
    Runtime: python3.13
    MemorySize: 256

Resources:
  ImageUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ImageUploadFunction
      Handler: src.main.handler
      CodeUri: ../
      Events:
        ApiUpload:
          Type: Api
          Properties:
            Path: /upload
            Method: post
      Environment:
        Variables:
          BUCKET_NAME: !Ref ImageBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref ImageBucket
        - CloudWatchPutMetricPolicy: {}

  ImageUploadLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ImageUploadFunction}"
      RetentionInDays: 7

  ImageResizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ImageResizeFunction
      Handler: src.resize.handler
      CodeUri: ../
      Environment:
        Variables:
          BUCKET_NAME: !Ref ImageBucket
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref ImageBucket
        - CloudWatchPutMetricPolicy: {}

  ImageResizeLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ImageResizeFunction}"
      RetentionInDays: 7
  
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-${AWS::AccountId}-images"
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Function: !GetAtt ImageResizeFunction.Arn

Outputs:
  ImageUploadApi:
    Description: "API Gateway endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/upload"
